### ISSUE TITLE
Possible missing dependencies

### ISSUE THREAD

**Issue by m33m33** [DimitriPapadopoulos/snapcraft_openfortivpn#2] opened 2020-04-01 08:15 UTC
It seems pppd is missing from the "parts" on the yaml file.

```
sudo openfortivpn-test.openfortivpn -u ... --persistent=10 ....
WARN: Could not load config file "/etc/openfortivpn/config" (Permission denied).
VPN account password:
INFO: Connected to gateway.
INFO: Authenticated.
INFO: Remote gateway has allocated a VPN.
ERROR: /usr/sbin/pppd: No such file or directory.
INFO: Closed connection to gateway.
INFO: Logged out.
^C
```

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 09:27
I have reused [`snapcraft.yaml`file by @devec0](https://github.com/devec0/openfortivpn/blob/add-snapcraft/snap/snapcraft.yaml). Among the differences with [yours](https://github.com/m33m33/snapcraft_openfortivpn/blob/master/snap/snapcraft.yaml):
* `confinement: strict` vs. `confinement: classic`
* `plugs: [network-bind]` vs. `plugs: [network, network-bind]`
* `stage-packages` and especially `ppp`

**Comment by m33m33** [comment] 2020-04-01 09:52
> I have reused [`snapcraft.yaml`file by @devec0](https://github.com/devec0/openfortivpn/blob/add-snapcraft/snap/snapcraft.yaml). Among the differences with [yours](https://github.com/m33m33/snapcraft_openfortivpn/blob/master/snap/snapcraft.yaml):
> 
> * `confinement: strict` vs. `confinement: classic`
> * `plugs: [network-bind]` vs. `plugs: [network, network-bind]`
> * `stage-packages` and especially `ppp`

Ok but... I don't see any stage pagackes in https://github.com/DimitriPapadopoulos/snapcraft_openfortivpn/blob/master/snap/snapcraft.yaml (?) and the current openfortivpn-test from your snapcraft.io depot seems to miss it.

In a freshly installed test VM, you may try this:
- install openfortivpn-test => openfortivpn-test fails because of pppd
- install openfortivpn (my snap) => openfortivpn-test AND openfortivpn OK
- remove openfortivpn (my snap) => openfortivpn-test fails because of pppd

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 10:19
I agree with you, there should be run-time dependencies. Yet the [`snapcraft.yaml`file by @devec0](https://github.com/devec0/openfortivpn/blob/add-snapcraft/snap/snapcraft.yaml) does not have run-time dependencies, only  build-time dependencies. I suspect he has not provided  the file used for the current 1.3.0 snap.

1. _openfortivpn_ requires _pppd_, hence `stage-packages: [ppp]` makes sense. By the way, does this mean _openfortivpn_ will use the system _pppd_, not embark its own?
2. I have tested the current 1.3.0 snap but it fails in `Gateway certificate validation`. I was able to work around this issue  by adding the 'trusted-cert' in the _openfortivpn_ config file. I'll have a look at this once I have fixed 1.

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 10:29
@m33m33 The snap work for me out-of-the-box on Ubuntu 18.04 LTS:

```
$ snap info openfortivpn-test 
name:      openfortivpn-test
summary:   openfortivpn, a PPP+SSL VPN client
publisher: Dimitri Papadopoulos
store-url: https://snapcraft.io/openfortivpn-test
license:   GPL-3.0
description: |
  **This is a test snap. Once it is ready I'll move it to James Hebden's snap:
  https://snapcraft.io/openfortivpn**
  
  Openfortivpn is a client for PPP+SSL VPN tunnel services.
  It spawns a pppd process and operates the communication between
  the gateway and this process.
commands:
  - openfortivpn-test.openfortivpn
snap-id:      Pae5Hbe6vW9VsM1g8k7xiA5262eextkA
tracking:     latest/edge
refresh-date: today at 12:22 CEST
channels:
  latest/stable:    –                            
  latest/candidate: 1.13.3 2020-03-30 (25) 118kB -
  latest/beta:      ↑                            
  latest/edge:      1.13.3 2020-03-31 (45) 118kB -
installed:          1.13.3            (45) 118kB -
$ 
$ cat ~/config 
host = xxxxx.xxxx.de
port = 443
username = xxxxxxx
password = xxxxxxxxxxxx
$ 
$ sudo /snap/openfortivpn-test/current/bin/openfortivpn -c ~/config 
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/3
INFO:   Got addresses: [10.212.134.200], ns [xxx.xx.xxx.252, xxx.xx.xxx.202]
INFO:   negotiation complete
INFO:   Got addresses: [10.212.134.200], ns [xxx.xx.xxx.252, xxx.xx.xxx.202]
INFO:   negotiation complete
INFO:   negotiation complete
local  IP address 10.212.134.200
remote IP address 192.0.2.1
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
```

Is that because the system _pppd_ is already installed on my Ubuntu 18.04 LTS machine?

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 10:51
On a Fedora 31 virtual machine:
```
$  sudo dnf install snapd
[...]
$ 
$  sudo snap install --edge openfortivpn-test
Warning: /var/lib/snapd/snap/bin was not found in your $PATH. If you've not restarted your session
         since you installed snapd, try doing that. Please see https://forum.snapcraft.io/t/9469
         for more details.

openfortivpn-test (edge) 1.13.3 from Dimitri Papadopoulos installed
$ 
$ snap info openfortivpn-test 
name:      openfortivpn-test
summary:   openfortivpn, a PPP+SSL VPN client
publisher: Dimitri Papadopoulos
store-url: https://snapcraft.io/openfortivpn-test
license:   GPL-3.0
description: |
  **This is a test snap. Once it is ready I'll move it to James Hebden's snap:
  https://snapcraft.io/openfortivpn**
  
  Openfortivpn is a client for PPP+SSL VPN tunnel services.
  It spawns a pppd process and operates the communication between
  the gateway and this process.
commands:
  - openfortivpn-test.openfortivpn
snap-id:      Pae5Hbe6vW9VsM1g8k7xiA5262eextkA
tracking:     latest/edge
refresh-date: today at 12:46 CEST
channels:
  stable:    –                            
  candidate: 1.13.3 2020-03-30 (25) 118kB -
  beta:      ↑                            
  edge:      1.13.3 2020-03-31 (45) 118kB -
installed:   1.13.3            (45) 118kB -
$ 
$ ldd /var/lib/snapd/snap/openfortivpn-test/current/bin/openfortivpn 
	linux-vdso.so.1 (0x00007ffddbdf4000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f7bf7243000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f7bf6f63000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f7bf6f5e000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7bf6f3c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7bf6d73000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f7bf6d59000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7bf6d50000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7bf750b000)
$ 
$ sudo /var/lib/snapd/snap/openfortivpn-test/current/bin/openfortivpn -c ~/config 
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/1
INFO:   Got addresses: [10.212.134.200], ns [xxx.xx.xxx.252, xxx.xx.xxx.202]
INFO:   negotiation complete
INFO:   Got addresses: [10.212.134.200], ns [xxx.xx.xxx.252, xxx.xx.xxx.202]
INFO:   negotiation complete
INFO:   negotiation complete
local  IP address 10.212.134.200
remote IP address 192.0.2.1
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.

```

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 11:02
This is on a vanilla _Fedora 31_ installation (_Workstation_). It looks like `pppd` is already installed. How did you install you own test VM?

Anyway, I have added `stage-packages: [ppp]` to the `snapcraft.yaml` file provided by @devec0. It is currently building.

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 12:24
My latest `openfprtivpn-snap` has been released:
```
        stage-packages:
            - ppp
```
@m33m33 Can you give it a try?

I think confinement issues are irrelevant for _openfortivpn_ because we execute the executable directly instead of executing the snap itself. Running the snap itself doesn't work because it cannot access configuration files outside of the snap:
``
$ sudo /snap/bin/openfortivpn-test.openfortivpn -c ~/config
WARN:   Could not load config file "/home/user/config" (Permission denied).
[...]
```

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 14:21
The dependency on _pppd_ should be fixed now. Closing this issue but please do not hesitate to re-open it if needed.

There's also the issue of how to access a configuration file but I'll open a different ticket for this one.

**Comment by m33m33** [comment] 2020-04-01 15:00
Now pppd is part of the openfortivpn-test snap. But it is at the wrong place...
```
(...)
ERROR:  /build/openfortivpn-test/parts/openfortivpn/install/usr/sbin/pppd: No such file or directory.
(...)
```
And it is:
```
find /snap/openfortivpn-test/ -name "pppd"
/snap/openfortivpn-test/68/usr/lib/pppd
/snap/openfortivpn-test/68/usr/sbin/pppd
/snap/openfortivpn-test/51/usr/lib/pppd
/snap/openfortivpn-test/51/usr/sbin/pppd
```

My guess it ./configure gets it during openfortivpn compilation, but this is not the definitive place of pppd in the released snap package file tree.

In my snap, it is at the same place:
```

find /snap/openfortivpn -name "pppd"
/snap/openfortivpn/x1/usr/lib/pppd
/snap/openfortivpn/x1/usr/sbin/pppd
```

You may want to look at my yaml file ./configure directives in the override-build section L46 https://github.com/m33m33/snapcraft_openfortivpn/blob/master/snap/snapcraft.yaml

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 16:02
Indeed but that's a slightly different issue:
* The run-time dependency on the system _pppd_ has been added with `stage-packages: [ppp]`.
* What you're seeing now is the effect of `plugs: [ppp]` which embarks a copy of _pppd_ in the snap instead of using the system _pppd_. I had added and have just removed `plugs: [ppp]` as this is clearly not what we want.

I suspect it might work with `confinement: classic` but I thought the whole point of snaps was to make them work with `confinement: strict`.

**Comment by m33m33** [comment] 2020-04-01 17:40
Well, for a network daemon like openfortivpn, I would say that `classic` is suitable.

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 21:43
The problem is that it gets very complicated to publish the snap. I'll keep digging into `strict` a little bit. If it doesn't work I may try to switch to `classic` and investigate how to get the snap approved.

What stumbles me is that current 1.3.0 snap is in `strict` mode:
https://git.launchpad.net/~ec0/+git/snap-openfortivpn/tree/snapcraft.yaml
Has it ever worked? Right now it fails at a very early stage, as if even the `network-bind` plug wasn't taken into account:
```
$ snap info openfortivpn
name:      openfortivpn
summary:   openfortivpn, a PPP+SSL VPN client
publisher: James Hebden (ec0)
store-url: https://snapcraft.io/openfortivpn
contact:   james.hebden@canonical.com
license:   unset
[...]
$ 
$ snap connections openfortivpn 
Interface     Plug                       Slot           Notes
network-bind  openfortivpn:network-bind  :network-bind  -
$ 
$ sudo /snap/bin/openfortivpn -u xxxxxxx xxxxx.xxxx.de:443
WARN:   Could not load config file "/etc/openfortivpn/config" (No such file or directory).
VPN account password: 
     12972:	2     12972:	     12972:	e.so.2ERROR:  gethostbyname: Unknown server error
INFO:   Closed connection to gateway.
ERROR:  connect: Connection refused
INFO:   Could not log out.
$ 
```
How do end-users even use it??? This doesn't make any sense. I suspect they execute `/snap/openfortivpn/current/bin/openfortivpn` instead of `/snap/bin/openfortivpn`.

**Comment by devec0** [comment] 2020-04-01 21:46
Hey @DimitriPapadopoulos, as I've mentioned before, I don't use this snap myself, just providing it to help the project. I have not relationship with the ~2000 people using this snap, so don't know if they are having any success using it. I was surprised to learn that this many people were using it, given it was not something I formally completed or used in production myself.

It's also entirely possibly that people are running the snap without issue, because my initial testing did show it working, but potentially changes in confinement to `snapd` or on your host operating system might be limiting things more now.

Regardless, it seems that adding the network, network-bind plugs resolves that, so you should do that. If you want to go down the classic confinement path, that may help with the issues you are seeing with PPP, but I think it would be best to raise the issues you are seeing the snapcraft forum, as you might be hitting a bug.

**Comment by DimitriPapadopoulos** [comment] 2020-04-01 21:59
Yes, I suspect something must have changed in confinement over the years. I'm using plain Ubuntu 18.04 myself, this is why I'm so surprised the initial 1.3.0 snap doesn't work here.

I'll follow your advice and ask on the snapcraft forum.

**Comment by DimitriPapadopoulos** [comment] 2020-04-02 09:13
Apart from the configuration file(s) issue which we can handle separately in #3, the last obstacle seems to be the lack of PPP support - with `sudo` only?

I have crated this topic in the forum:
[ppp plug, “/dev/ppp device: Permission denied” and sudo](https://forum.snapcraft.io/t/ppp-plug-dev-ppp-device-permission-denied-and-sudo/16366)

**Comment by DimitriPapadopoulos** [comment] 2020-04-02 14:34
Works like a charm with these plugs, thanks to suggestions from the Snapcraft forum:
```
        plugs:
            - network-bind
            - ppp
            - network-control
```

**Closed by DimitriPapadopoulos** 2020-04-02 14:34 UTC
